import Image from 'next/image';import Link from 'next/link';import { ArrowRight, Bot, ChartNoAxesCombined, FileText, Gauge, ShieldCheck, Sparkles, Target, Zap } from 'lucide-react';import PostCard from '@/components/PostCard';import Reveal from '@/components/Reveal';import { getAllPosts } from '@/lib/content';
export const revalidate = 60;
export default async function Home(){const posts = await getAllPosts();return <main>
<section className="hero"><Image src="/hero-ai.svg" alt="AI Marketing Automation" fill priority className="hero-bg"/><div className="hero-overlay"/><div className="container hero-content"><div className="eyebrow"><Sparkles size={15}/> AI & MARKETING AUTOMATION</div><h1>Tự động hóa Marketing.<br/><span>Tăng trưởng bền vững cùng AI.</span></h1><p>Kiến thức và giải pháp thực tiễn giúp doanh nghiệp tối ưu quy trình marketing, tiết kiệm chi phí và ra quyết định dựa trên dữ liệu.</p><div className="hero-actions"><Link className="btn btn-primary btn-lg" href="/dich-vu">Khám phá dịch vụ <ArrowRight size={18}/></Link><Link className="btn btn-glass btn-lg" href="/blog">Xem bài viết</Link></div></div></section>
<section className="benefits"><div className="container benefits-grid">{[[Zap,'Tự động hóa bằng AI','Giảm việc thủ công và tăng tốc vận hành.'],[Target,'Tăng trưởng bền vững','Chiến lược dựa trên dữ liệu và mục tiêu rõ.'],[Gauge,'Tối ưu chi phí','Tập trung ngân sách vào kênh tạo hiệu quả.'],[ShieldCheck,'Dữ liệu minh bạch','Đo lường rõ ràng và báo cáo dễ theo dõi.']].map(([I,t,d]:any)=><div className="benefit" key={t}><span className="benefit-icon"><I/></span><div><b>{t}</b><p>{d}</p></div></div>)}</div></section>
<Reveal><section className="section"><div className="container"><div className="section-head"><div><span className="kicker">INSIGHTS</span><h2>Bài viết mới nhất</h2></div><Link href="/blog" className="text-link">Xem tất cả <ArrowRight size={16}/></Link></div><div className="home-blog"><div className="post-grid">{posts.slice(0,3).map(p=><PostCard key={p.slug} post={p}/>)}</div><aside className="sidebar"><div className="newsletter"><span className="mini-icon"><Bot/></span><h3>Nhận bản tin Martech</h3><p>Tóm tắt xu hướng Marketing & AI mới, gửi định kỳ.</p><input placeholder="Email của bạn"/><button className="btn btn-primary">Đăng ký ngay</button></div><div className="popular"><h3>Bài đọc nhiều</h3>{posts.slice(3,6).map((p,i)=><Link href={`/blog/${p.slug}`} key={p.slug}><span>0{i+1}</span><b>{p.title}</b></Link>)}</div></aside></div></div></section></Reveal>
<Reveal><section className="section soft"><div className="container"><div className="section-head"><div><span className="kicker">SERVICES</span><h2>Nhóm giải pháp nổi bật</h2></div></div><div className="service-grid">{[[Bot,'AI Automation','Thiết kế workflow tự động cho marketing và chăm sóc khách hàng.'],[ChartNoAxesCombined,'Performance Marketing','Tối ưu chiến dịch theo dữ liệu, tập trung ROI và conversion.'],[FileText,'Content & SEO','Xây hệ thống nội dung giúp tăng organic traffic và độ tin cậy.']].map(([I,t,d]:any)=><div className="service-card" key={t}><span><I/></span><h3>{t}</h3><p>{d}</p><Link href="/dich-vu">Tìm hiểu <ArrowRight size={16}/></Link></div>)}</div></div></section></Reveal>
<section className="stats"><div className="container stats-grid">{[['AI Automation','Tự động hóa quy trình marketing'],['Performance','Tối ưu chiến dịch theo dữ liệu'],['Content & SEO','Xây nội dung bền vững, dễ tìm thấy'],['Analytics','Đo lường và cải thiện liên tục']].map(x=><div key={x[0]}><strong>{x[0]}</strong><span>{x[1]}</span></div>)}</div></section>
</main>}
