export type Post = {
  slug: string; title: string; excerpt: string; category: string; date: string; readTime: string; image: string; content: string[];
};
export const posts: Post[] = [
 {slug:'ai-marketing-la-gi',title:'AI Marketing là gì? Ứng dụng AI để tăng hiệu quả chiến dịch',excerpt:'Cách doanh nghiệp dùng AI để tối ưu nội dung, phân tích dữ liệu và tự động hóa marketing.',category:'AI Marketing',date:'15 Tháng 8, 2026',readTime:'7 phút đọc',image:'/article-1.svg',content:['AI Marketing là việc ứng dụng trí tuệ nhân tạo vào các hoạt động marketing để xử lý dữ liệu nhanh hơn, cá nhân hóa trải nghiệm và tự động hóa các tác vụ lặp lại.','Doanh nghiệp có thể bắt đầu từ những bài toán nhỏ như gợi ý nội dung, phân nhóm khách hàng, tối ưu lịch đăng hoặc hỗ trợ chăm sóc khách hàng.','Giá trị lớn nhất không nằm ở việc dùng thật nhiều công cụ AI, mà ở chỗ chọn đúng quy trình để tự động hóa và đo được kết quả.']},
 {slug:'marketing-automation-2026',title:'Marketing Automation 2026: Xu hướng tất yếu cho doanh nghiệp',excerpt:'Từ lead nurturing đến báo cáo tự động, automation giúp đội ngũ tiết kiệm thời gian và vận hành nhất quán.',category:'Automation',date:'12 Tháng 8, 2026',readTime:'6 phút đọc',image:'/article-2.svg',content:['Marketing Automation giúp kết nối nhiều bước trong hành trình khách hàng thành một quy trình có thể theo dõi và tối ưu.','Một hệ thống tốt cần dữ liệu sạch, trigger rõ ràng và nội dung phù hợp từng giai đoạn.','Hãy bắt đầu bằng một workflow nhỏ, đo conversion rồi mới mở rộng.']},
 {slug:'content-marketing-chien-luoc',title:'Content Marketing: Chiến lược xây dựng thương hiệu bền vững',excerpt:'Xây hệ thống nội dung có chủ đích thay vì đăng bài rời rạc để tăng độ tin cậy và chuyển đổi.',category:'Content Marketing',date:'10 Tháng 8, 2026',readTime:'5 phút đọc',image:'/article-3.svg',content:['Content Marketing hiệu quả cần bám sát câu hỏi và nhu cầu thực tế của khách hàng.','Thay vì chỉ viết bài SEO, hãy xây cụm nội dung có vai trò rõ ràng: thu hút, giáo dục, chứng minh và chuyển đổi.','Sự nhất quán về chủ đề, giọng điệu và trải nghiệm đọc giúp thương hiệu trở nên đáng nhớ hơn.']},
 {slug:'phan-tich-du-lieu-marketing',title:'Cách phân tích dữ liệu khách hàng để tối ưu chiến dịch marketing',excerpt:'Một khung đơn giản để đọc dữ liệu đúng, tránh chạy theo vanity metrics và tập trung vào hiệu quả kinh doanh.',category:'Analytics',date:'08 Tháng 8, 2026',readTime:'8 phút đọc',image:'/article-4.svg',content:['Dữ liệu chỉ có giá trị khi gắn với quyết định cụ thể.','Thay vì nhìn mọi chỉ số, hãy chọn vài KPI liên quan trực tiếp đến mục tiêu như cost per lead, conversion rate và revenue contribution.','Khi phân tích, cần so sánh theo thời gian, theo kênh và theo nhóm khách hàng để tìm ra nguyên nhân thay đổi.']},
 {slug:'seo-technical-checklist',title:'Technical SEO Checklist cho website nội dung',excerpt:'Các hạng mục cơ bản giúp bot crawl dễ hơn và người dùng có trải nghiệm ổn định.',category:'SEO',date:'05 Tháng 8, 2026',readTime:'6 phút đọc',image:'/article-2.svg',content:['Technical SEO tốt giúp công cụ tìm kiếm hiểu cấu trúc website và giảm lỗi index.','Các hạng mục cơ bản gồm sitemap, robots, canonical, metadata, tốc độ tải trang, cấu trúc heading và liên kết nội bộ.','Nên kiểm tra định kỳ sau mỗi lần thay đổi lớn về giao diện hoặc routing.']},
 {slug:'social-media-framework',title:'Social Media Framework: từ nội dung đến chuyển đổi',excerpt:'Xây một framework social gọn, dễ vận hành và có số liệu để tối ưu.',category:'Social Media',date:'03 Tháng 8, 2026',readTime:'5 phút đọc',image:'/article-1.svg',content:['Social Media nên được thiết kế như một hệ thống chứ không chỉ là lịch đăng bài.','Mỗi nhóm nội dung cần một mục tiêu: reach, engagement, trust hoặc conversion.','Sau vài tuần, dựa trên dữ liệu để tăng tỷ trọng các format có hiệu quả thực tế.']}
];
export const getPost = (slug:string)=>posts.find(p=>p.slug===slug);
