export type Post = {
  slug: string;
  title: string;
  excerpt: string;
  category: string;
  date: string;
  publishedAtISO: string;
  readTime: string;
  image: string;
  author: string;
  authorRole?: string;
  tags: string[];
  content: string[];
};

// Ảnh minh hoạ (Unsplash) — dùng qua <SafeImage> nên nếu ảnh lỗi sẽ tự rơi về ảnh local, không vỡ layout.
const cover = (id: string, w = 1200) => `https://images.unsplash.com/photo-${id}?auto=format&fit=crop&w=${w}&q=80`;
const IMG = {
  code1: cover('1498050108023-c5249f4df085'),
  code2: cover('1461749280684-dccba630e2f6'),
  team1: cover('1519389950473-47ba0277781c'),
  analytics: cover('1460925895917-afdab827c52f'),
  ai: cover('1518186285589-2f7649de83e0'),
  workspace: cover('1504384308090-c894fdcc538d'),
  meeting: cover('1556761175-5973dc0f32e7'),
  social: cover('1533750349088-cd871a92f312'),
  matrix: cover('1432888622747-4eb9a8efeb07'),
  circuit: cover('1518770660439-4636190af475'),
  gaming: cover('1550745165-9bc0b252726f'),
  screen: cover('1522202176988-66273c2fd55f'),
};

export const CATEGORY_GROUPS: { group: string; slug: string; categories: string[] }[] = [
  { group: 'Công nghệ', slug: 'cong-nghe', categories: ['Công nghệ', 'Trí tuệ nhân tạo', 'Phần mềm', 'Internet'] },
  { group: 'Marketing', slug: 'marketing', categories: ['Marketing', 'SEO', 'Content Marketing', 'Automation'] },
];

export const ALL_CATEGORIES = CATEGORY_GROUPS.flatMap((g) => g.categories);

export const posts: Post[] = [
  {
    slug: 'xu-huong-cong-nghe-doanh-nghiep-2026',
    title: '5 xu hướng công nghệ định hình doanh nghiệp năm 2026',
    excerpt: 'Từ AI tạo sinh đến điện toán biên, đây là những xu hướng công nghệ doanh nghiệp cần theo dõi trong năm 2026.',
    category: 'Công nghệ',
    date: '05 Tháng 9, 2026',
    publishedAtISO: '2026-09-05',
    readTime: '7 phút đọc',
    image: IMG.circuit,
    author: 'Minh Khang',
    authorRole: 'Biên tập Công nghệ',
    tags: ['công nghệ', 'xu hướng', 'doanh nghiệp'],
    content: [
      'Tốc độ ứng dụng công nghệ mới vào vận hành doanh nghiệp đang nhanh hơn bao giờ hết. Việc đứng ngoài cuộc không còn là lựa chọn an toàn, mà là rủi ro cạnh tranh thực sự.',
      'Dưới đây là 5 xu hướng công nghệ được nhắc đến nhiều nhất trong các báo cáo ngành gần đây, cùng góc nhìn thực tế về mức độ sẵn sàng áp dụng cho doanh nghiệp vừa và nhỏ.',
      '## 1. AI tạo sinh đi vào vận hành hằng ngày',
      'Không còn dừng ở việc viết nội dung, AI tạo sinh đang được tích hợp vào quy trình chăm sóc khách hàng, phân tích dữ liệu và cả thiết kế sản phẩm.',
      '## 2. Điện toán biên (Edge Computing)',
      'Dữ liệu được xử lý gần nguồn phát sinh hơn, giảm độ trễ và chi phí băng thông — phù hợp với các mô hình cần phản hồi tức thời như bán lẻ hoặc IoT.',
      '- AI tạo sinh (Generative AI) trong vận hành',
      '- Điện toán biên (Edge Computing)',
      '- Bảo mật theo mô hình Zero Trust',
      '- Nền tảng low-code/no-code',
      '- Tự động hoá quy trình bằng workflow thông minh',
      'Doanh nghiệp không cần chạy theo mọi xu hướng cùng lúc. Cách tiếp cận hợp lý là chọn 1–2 công nghệ có tác động rõ nhất đến bài toán hiện tại, thử nghiệm ở quy mô nhỏ rồi mới mở rộng.',
    ],
  },
  {
    slug: 'edge-computing-la-gi',
    title: 'Điện toán biên (Edge Computing) là gì và vì sao doanh nghiệp cần quan tâm',
    excerpt: 'Giải thích dễ hiểu về điện toán biên, sự khác biệt với điện toán đám mây và các trường hợp nên áp dụng.',
    category: 'Công nghệ',
    date: '30 Tháng 8, 2026',
    publishedAtISO: '2026-08-30',
    readTime: '6 phút đọc',
    image: IMG.screen,
    author: 'Quốc Bảo',
    authorRole: 'Software Engineer',
    tags: ['công nghệ', 'edge computing', 'hạ tầng'],
    content: [
      'Điện toán biên (Edge Computing) là mô hình xử lý dữ liệu ngay tại hoặc gần nơi dữ liệu được tạo ra, thay vì gửi toàn bộ về trung tâm dữ liệu hay đám mây rồi mới xử lý.',
      'Cách tiếp cận này giúp giảm độ trễ, tiết kiệm băng thông và cho phép ứng dụng phản hồi gần như tức thời — điều rất quan trọng với các hệ thống cần ra quyết định nhanh.',
      '## So với điện toán đám mây',
      'Cloud tập trung dữ liệu để dễ quản lý và mở rộng, còn Edge phân tán việc xử lý ra gần người dùng hoặc thiết bị. Hai mô hình không loại trừ nhau mà thường được kết hợp: Edge xử lý phần cần nhanh, Cloud lưu trữ và phân tích tổng thể.',
      '- Camera AI phát hiện sự cố tại nhà máy theo thời gian thực',
      '- Thiết bị IoT trong nông nghiệp thông minh',
      '- Ứng dụng bán lẻ cần phản hồi tức thời tại cửa hàng',
      'Với doanh nghiệp vừa và nhỏ, Edge Computing chưa chắc là ưu tiên ngay, nhưng hiểu đúng khái niệm sẽ giúp lựa chọn nhà cung cấp hạ tầng phù hợp khi hệ thống mở rộng.',
    ],
  },
  {
    slug: 'so-sanh-nen-tang-cloud-cho-sme',
    title: 'So sánh các nền tảng Cloud phổ biến cho doanh nghiệp vừa và nhỏ',
    excerpt: 'Điểm mạnh, điểm yếu và chi phí ước tính của các nền tảng đám mây phổ biến, giúp SME chọn đúng ngay từ đầu.',
    category: 'Công nghệ',
    date: '22 Tháng 8, 2026',
    publishedAtISO: '2026-08-22',
    readTime: '8 phút đọc',
    image: IMG.workspace,
    author: 'Quốc Bảo',
    authorRole: 'Software Engineer',
    tags: ['công nghệ', 'cloud', 'hạ tầng'],
    content: [
      'Chọn sai nền tảng cloud ngay từ đầu khiến nhiều doanh nghiệp phải di chuyển hệ thống giữa chừng — tốn thời gian và rủi ro gián đoạn dịch vụ.',
      'Bài viết tổng hợp các tiêu chí quan trọng nhất khi so sánh nền tảng đám mây, thay vì chỉ nhìn vào bảng giá.',
      '## Tiêu chí nên ưu tiên',
      '- Chi phí thực tế khi mở rộng, không chỉ giá khởi điểm',
      '- Hệ sinh thái dịch vụ đi kèm (CDN, database, bảo mật)',
      '- Chất lượng tài liệu và cộng đồng hỗ trợ',
      '- Khả năng tương thích với đội ngũ kỹ thuật hiện có',
      'Với doanh nghiệp mới bắt đầu, một nền tảng có gói miễn phí đủ dùng để thử nghiệm sản phẩm, tài liệu rõ ràng, thường quan trọng hơn việc chọn nền tảng "mạnh nhất" trên thị trường.',
      'Nguyên tắc chung: chọn nền tảng phù hợp với quy mô hiện tại và có đường đi rõ ràng để mở rộng, thay vì tối ưu cho một quy mô chưa chắc doanh nghiệp đạt tới.',
    ],
  },
  {
    slug: 'bao-mat-du-lieu-doanh-nghiep-co-ban',
    title: 'Bảo mật dữ liệu doanh nghiệp: những nguyên tắc cơ bản không thể bỏ qua',
    excerpt: 'Không cần đội ngũ bảo mật riêng, doanh nghiệp vẫn có thể giảm phần lớn rủi ro với vài nguyên tắc nền tảng.',
    category: 'Công nghệ',
    date: '14 Tháng 8, 2026',
    publishedAtISO: '2026-08-14',
    readTime: '6 phút đọc',
    image: IMG.matrix,
    author: 'Minh Khang',
    authorRole: 'Biên tập Công nghệ',
    tags: ['công nghệ', 'bảo mật', 'dữ liệu'],
    content: [
      'Phần lớn sự cố bảo mật ở doanh nghiệp vừa và nhỏ không đến từ các cuộc tấn công tinh vi, mà từ những lỗ hổng cơ bản: mật khẩu yếu, phân quyền lỏng lẻo, thiếu sao lưu dữ liệu.',
      '## Những việc nên làm trước tiên',
      '- Bật xác thực hai lớp (2FA) cho toàn bộ tài khoản quản trị',
      '- Phân quyền truy cập theo nguyên tắc "cần mới cấp"',
      '- Sao lưu dữ liệu định kỳ và kiểm tra khôi phục thử',
      '- Cập nhật phần mềm và vá lỗi thường xuyên',
      'Ngoài kỹ thuật, yếu tố con người vẫn là mắt xích yếu nhất. Một buổi đào tạo ngắn về nhận diện email lừa đảo có thể ngăn được phần lớn sự cố phổ biến nhất hiện nay.',
      'Bảo mật không phải một dự án làm một lần rồi xong, mà là thói quen vận hành cần duy trì liên tục.',
    ],
  },
  {
    slug: 'ai-marketing-la-gi',
    title: 'AI Marketing là gì? Ứng dụng AI để tăng hiệu quả chiến dịch',
    excerpt: 'Cách doanh nghiệp dùng AI để tối ưu nội dung, phân tích dữ liệu và tự động hóa marketing.',
    category: 'Trí tuệ nhân tạo',
    date: '03 Tháng 9, 2026',
    publishedAtISO: '2026-09-03',
    readTime: '7 phút đọc',
    image: IMG.ai,
    author: 'Đức Anh',
    authorRole: 'AI Researcher',
    tags: ['AI', 'marketing', 'automation'],
    content: [
      'AI Marketing là việc ứng dụng trí tuệ nhân tạo vào các hoạt động marketing để xử lý dữ liệu nhanh hơn, cá nhân hóa trải nghiệm và tự động hóa các tác vụ lặp lại.',
      'Doanh nghiệp có thể bắt đầu từ những bài toán nhỏ như gợi ý nội dung, phân nhóm khách hàng, tối ưu lịch đăng hoặc hỗ trợ chăm sóc khách hàng.',
      '## Bắt đầu từ đâu',
      '- Chọn một quy trình lặp lại, tốn nhiều thời gian thủ công',
      '- Thử nghiệm công cụ AI ở quy mô nhỏ, đo lường kết quả rõ ràng',
      '- Chuẩn hoá dữ liệu đầu vào trước khi mở rộng ứng dụng AI',
      'Giá trị lớn nhất không nằm ở việc dùng thật nhiều công cụ AI, mà ở chỗ chọn đúng quy trình để tự động hóa và đo được kết quả thực tế mang lại.',
    ],
  },
  {
    slug: 'ai-trong-giao-duc',
    title: 'Trí tuệ nhân tạo trong giáo dục: 5 ứng dụng đang thay đổi cách chúng ta học',
    excerpt: 'Từ gia sư ảo đến chấm bài tự động, AI đang len lỏi vào lớp học theo cách nhiều người chưa để ý.',
    category: 'Trí tuệ nhân tạo',
    date: '19 Tháng 8, 2026',
    publishedAtISO: '2026-08-19',
    readTime: '6 phút đọc',
    image: IMG.team1,
    author: 'Đức Anh',
    authorRole: 'AI Researcher',
    tags: ['AI', 'giáo dục', 'công nghệ'],
    content: [
      'Giáo dục là một trong những lĩnh vực được kỳ vọng thay đổi rõ rệt nhất nhờ AI, không phải để thay thế giáo viên mà để cá nhân hoá việc học cho từng người.',
      '## 5 ứng dụng đáng chú ý',
      '- Gia sư ảo trả lời câu hỏi theo tốc độ học của từng học viên',
      '- Chấm bài và phản hồi tự động cho các dạng bài trắc nghiệm, tự luận ngắn',
      '- Gợi ý lộ trình học phù hợp năng lực và mục tiêu',
      '- Dịch và phụ đề tự động giúp tiếp cận tài liệu đa ngôn ngữ',
      '- Phân tích dữ liệu học tập để phát hiện sớm học viên có nguy cơ bỏ học',
      'Thách thức lớn nhất không phải công nghệ, mà là cách thiết kế trải nghiệm học sao cho AI hỗ trợ đúng lúc mà không làm giảm vai trò chủ động của người học.',
    ],
  },
  {
    slug: 'chatbot-ai-cham-soc-khach-hang',
    title: 'Chatbot AI: từ chăm sóc khách hàng đến trợ lý bán hàng tự động',
    excerpt: 'Chatbot AI hiện đại không chỉ trả lời câu hỏi thường gặp mà còn có thể tư vấn và chốt đơn.',
    category: 'Trí tuệ nhân tạo',
    date: '09 Tháng 8, 2026',
    publishedAtISO: '2026-08-09',
    readTime: '5 phút đọc',
    image: IMG.social,
    author: 'Đức Anh',
    authorRole: 'AI Researcher',
    tags: ['AI', 'chatbot', 'bán hàng'],
    content: [
      'Thế hệ chatbot AI mới có thể hiểu ngữ cảnh hội thoại, ghi nhớ lịch sử trao đổi và đưa ra gợi ý sản phẩm phù hợp thay vì chỉ trả lời theo kịch bản cố định.',
      'Với doanh nghiệp nhỏ, một chatbot được huấn luyện đúng dữ liệu sản phẩm có thể xử lý phần lớn câu hỏi lặp lại, giải phóng thời gian cho đội ngũ tư vấn xử lý các ca phức tạp hơn.',
      '## Lưu ý khi triển khai',
      '- Luôn có lối chuyển sang nhân viên thật khi chatbot không xử lý được',
      '- Cập nhật dữ liệu sản phẩm, chính sách thường xuyên',
      '- Theo dõi các câu hỏi chatbot trả lời sai để cải thiện liên tục',
      'Chatbot không nên được xem là giải pháp thay thế hoàn toàn con người, mà là lớp hỗ trợ đầu tiên giúp phản hồi khách hàng nhanh hơn 24/7.',
    ],
  },
  {
    slug: 'chon-nen-tang-ban-khoa-hoc-online',
    title: 'Nền tảng bán khóa học online là gì, chọn sao cho đúng',
    excerpt: 'Việc có quá nhiều lựa chọn đôi khi lại là một vấn đề. Đây là khung tiêu chí giúp bạn chọn đúng ngay từ đầu.',
    category: 'Phần mềm',
    date: '19 Tháng 8, 2026',
    publishedAtISO: '2026-08-19',
    readTime: '6 phút đọc',
    image: IMG.code1,
    author: 'Quốc Bảo',
    authorRole: 'Software Engineer',
    tags: ['phần mềm', 'e-learning', 'kinh doanh online'],
    content: [
      'Việc có quá nhiều lựa chọn đôi khi lại là một vấn đề. Bạn mở một nền tảng học online, thấy hàng trăm khóa học với tiêu đề hấp dẫn, đánh giá 5 sao, và ưu đãi giảm giá 50%.',
      'Nhưng nền tảng phù hợp không nằm ở giao diện đẹp, mà ở khả năng đáp ứng đúng nhu cầu vận hành: thanh toán, cấp chứng chỉ, tương tác học viên và báo cáo doanh thu.',
      '## Tiêu chí lựa chọn',
      '- Chi phí nền tảng tính theo doanh thu hay phí cố định',
      '- Khả năng tùy biến giao diện, thương hiệu riêng',
      '- Công cụ marketing tích hợp: affiliate, mã giảm giá, email',
      '- Chất lượng phát video và trải nghiệm trên di động',
      'Trước khi quyết định, hãy dùng thử ở gói miễn phí hoặc thấp nhất, xuất bản một khóa học nhỏ để trải nghiệm toàn bộ quy trình từ tạo nội dung đến khi học viên thanh toán thành công.',
    ],
  },
  {
    slug: 'so-sanh-cong-cu-quan-ly-du-an',
    title: 'So sánh 5 công cụ quản lý dự án phổ biến cho đội nhóm nhỏ',
    excerpt: 'Không có công cụ nào "tốt nhất cho tất cả" — chỉ có công cụ phù hợp nhất với cách đội nhóm bạn làm việc.',
    category: 'Phần mềm',
    date: '11 Tháng 8, 2026',
    publishedAtISO: '2026-08-11',
    readTime: '7 phút đọc',
    image: IMG.meeting,
    author: 'Quốc Bảo',
    authorRole: 'Software Engineer',
    tags: ['phần mềm', 'quản lý dự án', 'năng suất'],
    content: [
      'Đội nhóm càng nhỏ, công cụ càng cần đơn giản. Một hệ thống quản lý dự án phức tạp có thể khiến team dành nhiều thời gian cập nhật trạng thái hơn là làm việc thật sự.',
      '## Nhóm tiêu chí nên so sánh',
      '- Mức độ trực quan của bảng công việc (kanban, timeline...)',
      '- Khả năng tích hợp với công cụ đang dùng (chat, lịch, tài liệu)',
      '- Tốc độ làm quen của thành viên mới',
      '- Chi phí theo số lượng người dùng khi đội nhóm mở rộng',
      'Một nguyên tắc hữu ích: chọn công cụ mà 80% thành viên có thể tự dùng thành thạo sau một buổi hướng dẫn ngắn, thay vì công cụ mạnh nhất nhưng cần đào tạo dài ngày.',
    ],
  },
  {
    slug: 'no-code-la-gi',
    title: 'No-code là gì? Xây sản phẩm số không cần biết lập trình',
    excerpt: 'No-code giúp người không rành kỹ thuật vẫn có thể tự dựng website, ứng dụng nội bộ hay quy trình tự động.',
    category: 'Phần mềm',
    date: '01 Tháng 8, 2026',
    publishedAtISO: '2026-08-01',
    readTime: '5 phút đọc',
    image: IMG.screen,
    author: 'Quốc Bảo',
    authorRole: 'Software Engineer',
    tags: ['phần mềm', 'no-code', 'sản phẩm số'],
    content: [
      'No-code là cách xây dựng ứng dụng, website hoặc quy trình tự động bằng thao tác kéo-thả, thay vì viết mã từ đầu. Điều này giúp rút ngắn đáng kể thời gian từ ý tưởng đến sản phẩm thử nghiệm.',
      '## Khi nào nên dùng no-code',
      '- Cần kiểm chứng ý tưởng nhanh trước khi đầu tư đội kỹ thuật',
      '- Xây công cụ nội bộ đơn giản: form, dashboard, quy trình phê duyệt',
      '- Tự động hoá các tác vụ lặp lại giữa nhiều phần mềm',
      'Giới hạn của no-code là khả năng tùy biến sâu và hiệu năng khi sản phẩm mở rộng quy mô lớn. Nhiều đội ngũ chọn no-code cho giai đoạn đầu, sau đó chuyển một phần sang code truyền thống khi cần.',
    ],
  },
  {
    slug: 'ma-qr-diem-cham-chuan',
    title: 'Mã QR: một điểm chạm chuẩn cho nhiều kênh',
    excerpt: 'Từ menu nhà hàng đến thanh toán, mã QR trở thành cầu nối gọn nhẹ giữa offline và online.',
    category: 'Internet',
    date: '17 Tháng 8, 2026',
    publishedAtISO: '2026-08-17',
    readTime: '4 phút đọc',
    image: IMG.social,
    author: 'Minh Khang',
    authorRole: 'Biên tập Công nghệ',
    tags: ['internet', 'công nghệ', 'trải nghiệm khách hàng'],
    content: [
      'Mã QR đã đi từ một công nghệ ít người để ý thành một điểm chạm quen thuộc: quét để xem menu, quét để thanh toán, quét để nhận ưu đãi.',
      'Điểm mạnh của mã QR là sự đơn giản — không cần cài đặt gì thêm, chỉ cần camera điện thoại. Điều này khiến nó phù hợp để kết nối trải nghiệm offline với các kênh online như website, mạng xã hội hay landing page khuyến mãi.',
      '## Vài nguyên tắc khi dùng mã QR trong marketing',
      '- Luôn dẫn đến một trang đích được tối ưu cho di động',
      '- Đặt mã QR ở nơi dễ quét, đủ ánh sáng và kích thước',
      '- Theo dõi lượt quét để đo hiệu quả từng điểm đặt mã',
      'Một mã QR tốt không chỉ là kỹ thuật, mà là một trải nghiệm liền mạch từ lúc quét đến lúc người dùng đạt được điều họ cần.',
    ],
  },
  {
    slug: 'toc-do-internet-anh-huong-seo',
    title: 'Tốc độ Internet ảnh hưởng thế nào đến trải nghiệm người dùng và SEO',
    excerpt: 'Một website tải chậm không chỉ khiến khách rời đi mà còn ảnh hưởng trực tiếp đến thứ hạng tìm kiếm.',
    category: 'Internet',
    date: '06 Tháng 8, 2026',
    publishedAtISO: '2026-08-06',
    readTime: '6 phút đọc',
    image: IMG.matrix,
    author: 'Lan Phương',
    authorRole: 'SEO Specialist',
    tags: ['internet', 'SEO', 'hiệu năng website'],
    content: [
      'Người dùng ngày nay có rất ít kiên nhẫn với một website tải chậm. Chỉ vài giây chờ đợi cũng đủ khiến một phần khách truy cập rời đi trước khi thấy nội dung.',
      '## Vì sao tốc độ ảnh hưởng đến SEO',
      'Các công cụ tìm kiếm ưu tiên trải nghiệm người dùng, trong đó tốc độ tải trang là một tín hiệu xếp hạng quan trọng, đặc biệt trên thiết bị di động.',
      '- Nén và tối ưu hình ảnh trước khi tải lên',
      '- Hạn chế script không cần thiết chặn hiển thị trang',
      '- Dùng bộ nhớ đệm (cache) và CDN cho nội dung tĩnh',
      'Tối ưu tốc độ không phải việc làm một lần. Nên kiểm tra định kỳ, đặc biệt sau khi thêm plugin, hình ảnh hoặc script mới vào website.',
    ],
  },
  {
    slug: 'marketing-chia-khoa-but-pha',
    title: 'Marketing – chìa khóa giúp doanh nghiệp bứt phá trong thời đại số',
    excerpt: 'Marketing hiện đại không còn là quảng cáo đơn thuần, mà là cách doanh nghiệp xây niềm tin và giữ chân khách hàng.',
    category: 'Marketing',
    date: '31 Tháng 8, 2026',
    publishedAtISO: '2026-08-31',
    readTime: '6 phút đọc',
    image: IMG.meeting,
    author: 'Hải Yến',
    authorRole: 'Performance Marketing Lead',
    tags: ['marketing', 'chiến lược', 'thương hiệu'],
    content: [
      'Trong một thị trường mà khách hàng có vô số lựa chọn, marketing không còn đơn thuần là quảng cáo mà là toàn bộ cách một doanh nghiệp xây dựng niềm tin, giữ chân khách hàng và tạo ra tăng trưởng bền vững.',
      '## Ba trụ cột của marketing hiện đại',
      '- Đúng đối tượng: hiểu rõ khách hàng thực sự cần gì',
      '- Đúng kênh: xuất hiện ở nơi khách hàng dành thời gian',
      '- Đúng thời điểm: giao tiếp đúng lúc khách hàng sẵn sàng ra quyết định',
      'Doanh nghiệp làm marketing tốt không phải doanh nghiệp chi nhiều tiền nhất, mà là doanh nghiệp đo lường tốt nhất — biết rõ đồng ngân sách nào đang tạo ra giá trị và đồng nào cần cắt bỏ.',
    ],
  },
  {
    slug: 'xay-dung-thuong-hieu-ca-nhan',
    title: 'Xây dựng thương hiệu cá nhân trên mạng xã hội: bắt đầu từ đâu',
    excerpt: 'Không cần nổi tiếng ngay, chỉ cần nhất quán. Đây là khung cơ bản để bắt đầu xây thương hiệu cá nhân.',
    category: 'Marketing',
    date: '23 Tháng 8, 2026',
    publishedAtISO: '2026-08-23',
    readTime: '5 phút đọc',
    image: IMG.social,
    author: 'Thảo Ngân',
    authorRole: 'Content Strategist',
    tags: ['marketing', 'thương hiệu cá nhân', 'social media'],
    content: [
      'Thương hiệu cá nhân không phải là việc cố gắng nổi tiếng, mà là việc để người khác nhớ đến bạn với một hình ảnh rõ ràng, nhất quán khi nhắc đến một chủ đề cụ thể.',
      '## Ba bước bắt đầu',
      '- Chọn một chủ đề cốt lõi bạn có thể nói sâu trong thời gian dài',
      '- Chọn 1–2 kênh phù hợp thay vì dàn trải trên tất cả nền tảng',
      '- Đăng đều đặn và giữ giọng điệu nhất quán qua từng bài viết',
      'Kết quả của thương hiệu cá nhân thường đến chậm nhưng bền: cơ hội hợp tác, khách hàng tin tưởng và mạng lưới quan hệ chất lượng hơn.',
    ],
  },
  {
    slug: 'pheu-marketing-hien-dai',
    title: 'Phễu marketing hiện đại: từ nhận biết đến trung thành',
    excerpt: 'Phễu marketing không dừng lại ở chuyển đổi — giữ chân khách hàng cũ mới là nơi tạo ra tăng trưởng bền vững.',
    category: 'Marketing',
    date: '13 Tháng 8, 2026',
    publishedAtISO: '2026-08-13',
    readTime: '6 phút đọc',
    image: IMG.analytics,
    author: 'Hải Yến',
    authorRole: 'Performance Marketing Lead',
    tags: ['marketing', 'phễu bán hàng', 'chiến lược'],
    content: [
      'Nhiều doanh nghiệp chỉ tập trung vào phần đầu phễu — làm sao có thêm khách truy cập, thêm lượt xem — mà bỏ quên phần cuối, nơi quyết định doanh thu thực sự.',
      '## Bốn giai đoạn cần được đầu tư đều',
      '- Nhận biết: khách hàng biết đến thương hiệu qua nội dung, quảng cáo',
      '- Cân nhắc: so sánh, tìm hiểu thêm thông tin, đọc đánh giá',
      '- Chuyển đổi: ra quyết định mua hoặc đăng ký',
      '- Trung thành: quay lại, giới thiệu cho người khác',
      'Một phễu khỏe mạnh cần được đo lường ở từng giai đoạn, thay vì chỉ nhìn vào một chỉ số duy nhất như số lượt truy cập hay số đơn hàng.',
    ],
  },
  {
    slug: 'seo-technical-checklist',
    title: 'Technical SEO Checklist cho website nội dung',
    excerpt: 'Các hạng mục cơ bản giúp bot crawl dễ hơn và người dùng có trải nghiệm ổn định.',
    category: 'SEO',
    date: '27 Tháng 8, 2026',
    publishedAtISO: '2026-08-27',
    readTime: '6 phút đọc',
    image: IMG.code2,
    author: 'Lan Phương',
    authorRole: 'SEO Specialist',
    tags: ['SEO', 'technical SEO', 'website'],
    content: [
      'Technical SEO tốt giúp công cụ tìm kiếm hiểu cấu trúc website và giảm lỗi index, tạo nền tảng để các nỗ lực nội dung phát huy hiệu quả.',
      '## Các hạng mục cơ bản',
      '- Sitemap và robots.txt được cấu hình đúng',
      '- Thẻ canonical rõ ràng cho từng trang',
      '- Metadata (title, description) đầy đủ và không trùng lặp',
      '- Cấu trúc heading hợp lý (H1 → H2 → H3)',
      '- Liên kết nội bộ giữa các bài viết liên quan',
      'Nên kiểm tra định kỳ sau mỗi lần thay đổi lớn về giao diện hoặc routing, vì đây là lúc dễ phát sinh lỗi 404 hoặc trùng lặp URL nhất.',
    ],
  },
  {
    slug: 'long-tail-keyword',
    title: 'Từ khóa dài (Long-tail keyword): vũ khí bị đánh giá thấp trong SEO',
    excerpt: 'Ít lượt tìm kiếm hơn nhưng tỷ lệ chuyển đổi cao hơn — đây là lý do từ khóa dài đáng được đầu tư.',
    category: 'SEO',
    date: '18 Tháng 8, 2026',
    publishedAtISO: '2026-08-18',
    readTime: '5 phút đọc',
    image: IMG.workspace,
    author: 'Lan Phương',
    authorRole: 'SEO Specialist',
    tags: ['SEO', 'từ khóa', 'content'],
    content: [
      'Nhiều người làm SEO chỉ tập trung vào các từ khóa ngắn, lượt tìm kiếm cao — nhưng đây cũng là nhóm từ khóa cạnh tranh khốc liệt nhất.',
      '## Vì sao từ khóa dài đáng đầu tư',
      'Từ khóa dài thường thể hiện ý định tìm kiếm rõ ràng hơn. Người tìm "cách chọn nền tảng bán khóa học online cho giáo viên tự do" gần với quyết định mua hơn nhiều so với người chỉ gõ "khóa học online".',
      '- Cạnh tranh thấp hơn, dễ lên top hơn với nội dung chất lượng',
      '- Tỷ lệ chuyển đổi thường cao hơn từ khóa ngắn',
      '- Phù hợp để xây cụm nội dung (topic cluster) chuyên sâu',
      'Chiến lược hiệu quả là kết hợp: từ khóa ngắn để xây độ nhận diện, từ khóa dài để thu hút đúng người sẵn sàng chuyển đổi.',
    ],
  },
  {
    slug: 'content-marketing-chien-luoc',
    title: 'Content Marketing: chiến lược xây dựng thương hiệu bền vững',
    excerpt: 'Xây hệ thống nội dung có chủ đích thay vì đăng bài rời rạc để tăng độ tin cậy và chuyển đổi.',
    category: 'Content Marketing',
    date: '28 Tháng 8, 2026',
    publishedAtISO: '2026-08-28',
    readTime: '5 phút đọc',
    image: IMG.team1,
    author: 'Thảo Ngân',
    authorRole: 'Content Strategist',
    tags: ['content marketing', 'thương hiệu', 'chiến lược'],
    content: [
      'Content Marketing hiệu quả cần bám sát câu hỏi và nhu cầu thực tế của khách hàng, thay vì chỉ sản xuất nội dung theo cảm hứng.',
      'Thay vì chỉ viết bài SEO đơn lẻ, hãy xây cụm nội dung có vai trò rõ ràng: thu hút, giáo dục, chứng minh và chuyển đổi.',
      '## Bốn vai trò của nội dung',
      '- Thu hút: nội dung dễ tiếp cận, giải quyết vấn đề phổ biến',
      '- Giáo dục: hướng dẫn chi tiết, giúp khách hàng hiểu sâu hơn',
      '- Chứng minh: case study, số liệu, đánh giá thực tế',
      '- Chuyển đổi: nội dung dẫn hành động cụ thể',
      'Sự nhất quán về chủ đề, giọng điệu và trải nghiệm đọc giúp thương hiệu trở nên đáng nhớ hơn theo thời gian.',
    ],
  },
  {
    slug: 'brand-storytelling',
    title: 'Kể chuyện thương hiệu (Brand Storytelling): công thức tạo nội dung khó quên',
    excerpt: 'Một câu chuyện được kể đúng cách khiến thương hiệu được nhớ lâu hơn bất kỳ thông điệp quảng cáo nào.',
    category: 'Content Marketing',
    date: '10 Tháng 8, 2026',
    publishedAtISO: '2026-08-10',
    readTime: '5 phút đọc',
    image: IMG.workspace,
    author: 'Thảo Ngân',
    authorRole: 'Content Strategist',
    tags: ['content marketing', 'storytelling', 'thương hiệu'],
    content: [
      'Con người ghi nhớ câu chuyện tốt hơn số liệu hay danh sách tính năng. Đó là lý do brand storytelling trở thành công cụ mạnh trong content marketing hiện đại.',
      '## Công thức kể chuyện đơn giản',
      '- Bối cảnh: khách hàng hoặc thương hiệu đang gặp vấn đề gì',
      '- Hành trình: những nỗ lực, thử nghiệm đã trải qua',
      '- Chuyển biến: điều gì đã thay đổi kết quả',
      '- Bài học: giá trị cốt lõi thương hiệu muốn truyền tải',
      'Một câu chuyện thương hiệu tốt không cần phóng đại. Sự chân thật và cụ thể luôn thuyết phục hơn những mỹ từ chung chung.',
    ],
  },
  {
    slug: 'marketing-automation-2026',
    title: 'Marketing Automation 2026: xu hướng tất yếu cho doanh nghiệp',
    excerpt: 'Từ lead nurturing đến báo cáo tự động, automation giúp đội ngũ tiết kiệm thời gian và vận hành nhất quán.',
    category: 'Automation',
    date: '26 Tháng 8, 2026',
    publishedAtISO: '2026-08-26',
    readTime: '6 phút đọc',
    image: IMG.analytics,
    author: 'Hải Yến',
    authorRole: 'Performance Marketing Lead',
    tags: ['automation', 'marketing', 'workflow'],
    content: [
      'Marketing Automation giúp kết nối nhiều bước trong hành trình khách hàng thành một quy trình có thể theo dõi và tối ưu, thay vì xử lý thủ công từng bước rời rạc.',
      '## Điều kiện để automation hiệu quả',
      '- Dữ liệu khách hàng sạch và được đồng bộ giữa các công cụ',
      '- Trigger (điều kiện kích hoạt) rõ ràng cho từng workflow',
      '- Nội dung phù hợp với từng giai đoạn của khách hàng',
      'Hãy bắt đầu bằng một workflow nhỏ — ví dụ gửi email chào mừng tự động — đo lường tỷ lệ mở và chuyển đổi, rồi mới mở rộng sang các kịch bản phức tạp hơn.',
    ],
  },
  {
    slug: 'tu-dong-hoa-cham-soc-khach-hang',
    title: 'Tự động hóa quy trình chăm sóc khách hàng bằng workflow đơn giản',
    excerpt: 'Không cần hệ thống phức tạp, một vài workflow cơ bản đã có thể cải thiện đáng kể trải nghiệm khách hàng.',
    category: 'Automation',
    date: '02 Tháng 8, 2026',
    publishedAtISO: '2026-08-02',
    readTime: '5 phút đọc',
    image: IMG.meeting,
    author: 'Hải Yến',
    authorRole: 'Performance Marketing Lead',
    tags: ['automation', 'chăm sóc khách hàng', 'workflow'],
    content: [
      'Không phải doanh nghiệp nào cũng cần một hệ thống automation phức tạp ngay từ đầu. Nhiều cải thiện đáng kể đến từ vài workflow đơn giản nhưng đúng chỗ.',
      '## Ba workflow nên có đầu tiên',
      '- Email/tin nhắn xác nhận và cảm ơn sau khi khách hàng mua hàng',
      '- Nhắc nhở tự động khi khách hàng bỏ giỏ hàng',
      '- Khảo sát mức độ hài lòng sau một khoảng thời gian sử dụng',
      'Mỗi workflow nên có một mục tiêu đo lường được — tỷ lệ mở, tỷ lệ phản hồi, hoặc tỷ lệ quay lại mua hàng — để biết chính xác nó đang tạo ra giá trị hay chỉ đang "chạy cho có".',
    ],
  },
];

export const getPost = (slug: string) => posts.find((p) => p.slug === slug);

export const AUTHORS = [
  {
    name: 'Đức Anh',
    role: 'AI Researcher',
    avatar: 'https://i.pravatar.cc/150?img=12',
    bio: 'Nghiên cứu ứng dụng AI trong marketing và tự động hoá, từng tư vấn triển khai chatbot cho nhiều doanh nghiệp vừa và nhỏ.',
  },
  {
    name: 'Minh Khang',
    role: 'Biên tập Công nghệ',
    avatar: 'https://i.pravatar.cc/150?img=13',
    bio: 'Theo dõi mảng công nghệ doanh nghiệp và hạ tầng số, ưu tiên nội dung dễ hiểu, có ví dụ thực tế thay vì thuật ngữ.',
  },
  {
    name: 'Thảo Ngân',
    role: 'Content Strategist',
    avatar: 'https://i.pravatar.cc/150?img=47',
    bio: 'Xây dựng chiến lược nội dung cho nhiều thương hiệu, tập trung vào content pillar và kể chuyện thương hiệu.',
  },
  {
    name: 'Hải Yến',
    role: 'Performance Marketing Lead',
    avatar: 'https://i.pravatar.cc/150?img=32',
    bio: 'Quản lý ngân sách quảng cáo đa kênh, tối ưu chiến dịch theo dữ liệu và ROI thực tế.',
  },
  {
    name: 'Quốc Bảo',
    role: 'Software Engineer',
    avatar: 'https://i.pravatar.cc/150?img=51',
    bio: 'Phát triển web và công cụ nội bộ, quan tâm đến hiệu năng hệ thống và trải nghiệm người dùng.',
  },
  {
    name: 'Lan Phương',
    role: 'SEO Specialist',
    avatar: 'https://i.pravatar.cc/150?img=45',
    bio: 'Chuyên về technical SEO và tối ưu nội dung, giúp website tăng traffic tự nhiên bền vững.',
  },
];
